/*
  Warnings:

  - You are about to alter the column `pid` on the `product` table. The data in that column will be cast from `BigInt` to `Int`. This cast may fail. Please make sure the data in the column can be cast.

*/
-- RedefineTables
CREATE TABLE "_prisma_new_product" (
    "pid" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "desc" STRING NOT NULL,
    "summary" STRING NOT NULL,
    "sellingPrice" FLOAT8 NOT NULL,
    "costPrice" FLOAT8 NOT NULL,
    "isFeatured" BOOL NOT NULL,

    CONSTRAINT "product_pkey" PRIMARY KEY ("pid")
);
INSERT INTO "_prisma_new_product" ("costPrice","desc","isFeatured","name","pid","sellingPrice","summary") SELECT "costPrice","desc","isFeatured","name","pid","sellingPrice","summary" FROM "product";
DROP TABLE "product" CASCADE;
ALTER TABLE "_prisma_new_product" RENAME TO "product";
